name: Java CI

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: |
        mkdir tmp
        mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |
        mkdir -p tmp
        sed -e 's/__USERNAME__/'"$BINTRAY_USERNAME"'/' -e 's/__PASSWORD__/'"$BINTRAY_API_KEY"'/' .github/workflows/settings.xml > tmp/settings.xml
        mvn deploy -s tmp/settings.xml
      env:
        BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
